name: ci
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress tests
        uses: cypress-io/github-action@v4
        with:
          build: npm run generate
          start: npm run start
